# Generated by Django 6.0.1 on 2026-01-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cars",
            new_name="Car",
        ),
    ]
