# Generated by Django 6.0.1 on 2026-01-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_category_delete_car"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
    ]
